### ISSUE TITLE
Update Twitter Icon on Website

### ISSUE THREAD

**Issue by Ayush9026** [vultr/vultr-csi#170]
**Description**
The current Twitter icon on our website appears to be outdated or incorrect. This issue is raised to track and address the update of the Twitter icon to ensure that it aligns with our branding and remains visually appealing.

**Current State**
Describe the current state of the Twitter icon on the website. Specify if it's outdated, incorrect, or if there are any issues with its appearance.
Marked in screenshot below.

![Vultr Website](https://github.com/vultr/vultr-csi/assets/114745463/24817553-f223-4bf6-9524-9fb3f01d83ef)

**Desired Changes**
New Icon: Provide a link or upload the new Twitter icon that should replace the current one.
Styling: If there are specific styling considerations (size, color, etc.), mention them here.
Example Code
If applicable, include code snippets related to updating the Twitter icon in the website's codebase.

**Benefits**
Keep the website's visual elements up-to-date.
Ensure consistency with our branding across all platforms.
Additional Notes
Double-check the licensing and permissions for the new icon.
Coordinate with the design team or responsible individuals for approval

**Comment by optik-aper** [comment]
@Ayush9026 This is for a Vultr open source project and isn't relevant to the website so I'm going to close this.

**Comment by optik-aper** [comment]
I'll pass along your feedback with the team that would be able to make this change
