### ISSUE TITLE
Question - how to define/select location?

### ISSUE THREAD

**Issue by zulhfreelancer** [vultr/vultr-csi#42]
I haven't tried this yet. But from the project README, I couldn't see anything related to selecting where the Block Storage (BS) should be located. From Vultr.com web UI, I saw 2 locations for BS.

![Block-Storage-Vultr](https://user-images.githubusercontent.com/3416976/119301389-fbc36380-bc94-11eb-9300-c54d3bdf2c37.png)

Can I define the BS location e.g. Los Angeles via Kubernetes YAML manifest?

**Comment by ddymko** [comment]
Hey @zulhfreelancer 

When the CSI is starting up it pulls down metadata about the instance it is running on :

https://github.com/vultr/vultr-csi/blob/master/driver/driver.go#L64
https://github.com/vultr/vultr-csi/blob/master/driver/driver.go#L79

This metadata contains the current region it is in. So if you deploy BS with a yaml definition in LA or NJ  it will have the region already defined.

**Comment by zulhfreelancer** [comment]
Thank you
