### ISSUE TITLE
How to use accessModes: ReadWriteMany 

### ISSUE THREAD

**Issue by Luskan777** [vultr/vultr-csi#51]
hi, 

I have a doubt regarding the volume access mode, is it possible to implement "accessModes: ReadWriteMany " ?
If yes, how to do this?

**Comment by ddymko** [comment]
@Luskan777 Vultr block storage, and this CSI, only supports `ReadWriteOnce` as we can only mount block storage to a single node at a time.

If you need ReadWriteMany you will have to deploy a custom solution....something like NFS for example.

**Comment by Luskan777** [comment]
Hi @ddymko ,

That's what I thought...

Thanks for your answer @ddymko !!
