### ISSUE TITLE
[Feature] - Nomad support

### ISSUE THREAD

**Issue by nahsi** [vultr/vultr-csi#64]
Is Nomad support planned?

In theory it [should work](https://www.nomadproject.io/docs/internals/plugins/csi) out of the box, but in practice many plugins are built with K8S in mind and do not adhere to csi specification.

I'm planning to test in very soon and I will share the result and, if it works, a deployment example.

**Comment by ddymko** [comment]
@nahsi 

We built the CSI following the CSI spec. I never tested it on nomad but would love to get your results and work on supporting nomad if there are things we are missing.

**Comment by nahsi** [comment]
I've been succesfully using Vultr CSI with Nomad for a week and it is 100% fine, I haven't had any issues. Thank you for writing this plugin!

I've created a PR with some examples of how to run and use Vultr CSI with Nomad, please have a look when you have time 🙇🏻‍♂️
