### ISSUE TITLE
[BUG] Failed to add block storage device. Invalid size (8GB) - Must be between 10GB and 10000GB.","status":400

### ISSUE THREAD

**Issue by suhaibaffan** [vultr/vultr-csi#86]
**Describe the bug**
When the pvc is less than 10 Gb it throws error:
```
failed to provision volume with StorageClass "vultr-block-storage": rpc error: code = Internal desc = {"error":"Unable to add block storage: Failed to add block storage device. Invalid size (8GB) - Must be between 10GB and 10000GB.","status":400}
```

**To Reproduce**
1. Create a PVC of volume 8Gb
2. See error

**Expected behavior**
The PVC volume claim should either fix the volume to 10Gb or should create volume as per the claim.

**Screenshots**
This makes it in `pending` state.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/18115937/177274079-48c3e078-a5a4-4bac-95b9-092f47ced67e.png">
 problem here.

**Comment by ddymko** [comment]
@suhaibaffan Vultr doesn't support block storage sizes less than 10 Gb (NVMe) and less than 40 Gb (HDD)

https://github.com/vultr/vultr-csi/tree/master/docs/kubernetes#nvme-block-type
https://github.com/vultr/vultr-csi/tree/master/docs/kubernetes#hdd-block-type


cc @optik-aper

**Comment by optik-aper** [comment]
Thanks for checking this @ddymko
